name: posyandu_cempaka2
description: "Aplikasi pendataan keluarga & balita Posyandu RW Cempaka 2"

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0

  # Form validation & UI
  flutter_form_builder: ^9.2.0 # (optional, bisa juga pakai form biasa)
  intl: ^0.19.0 # untuk formatting tanggal dll

  # UI improvement
  flutter_spinkit: ^5.2.0 # loading indicator
  fluttertoast: ^8.2.4 # snackbar/toast

  #Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/

fonts:
  -family: Poppins
  fonts:
    - assets: fonts/Poppins-Bold.ttf
      weight: 700
    - assets: fonts/Poppins-Medium.ttf
      weight: 500
    - assets: fonts/Poppins-Regular.ttf
      weight: 400
    - assets: fonts/Poppins-SemiBold.ttf
      weight: 600
